version: '2'
services:
  redis-master:
    image: redis:latest
    volumes:
        - ./data/redis/:/data
    ports:
        - "6379:6379"
  mysql-master:
    image: mysql:5.7
    volumes:
        - ./data/mysql/:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw